GET http://localhost:8000/users HTTP/1.1

###

GET http://localhost:8000/users/100 HTTP/1.1

###
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=109&userName=jcote&age=66